<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>CL Syntax: version 0.2</string>
	<key>fileTypes</key>
	<array>
		<string>cl</string>
		<string>clx</string>
		<string>clang</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^\s*\b(function|if|for)\b|{[ \t]*$|\[\[</string>
	<key>foldingStopMarker</key>
	<string>\b}\;\b|^\s*}\;|\]\]</string>
	<key>keyEquivalent</key>
	<string>^~L</string>
	<key>name</key>
	<string>CL</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.cl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.cl</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.cl</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.cl</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.cl</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.cl</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(type)\s+([a-zA-Z0-9_]+)\s*([:]+)\s*([A-Za-z0-9_\$,\s]+)\s*(\=)\s*([\"\'A-Za-z0-9_\$,\s=]+)</string>
			<key>name</key>
			<string>meta.function.cl</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.cl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.cl</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.cl</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.cl</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(function)\s+([a-zA-Z0-9_]+)\s*([:]+)\s*([A-Za-z0-9_\$,\s]+)</string>
			<key>name</key>
			<string>meta.function.cl</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.cl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.cl</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.cl</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b([\@a-zA-Z0-9_]+)\s*([:]+)\s*([A-Za-z0-9_\$,\s]+)</string>
			<key>name</key>
			<string>meta.function.cl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;![\d.])\s0x[a-fA-F\d]+|\b\d+(\.\d+)?([eE]-?\d+)?|\.\d+([eE]-?\d+)?</string>
			<key>name</key>
			<string>constant.numeric.cl</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.cl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.cl</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.cl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.cl</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.cl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.cl</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.cl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.cl</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;!--)\[(=*)\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.cl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]\1\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.cl</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.other.multiline.cl</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\[\#</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.cl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\#\]</string>
			<key>name</key>
			<string>comment.block.cl</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.cl</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\#\#).*$\n?</string>
			<key>name</key>
			<string>comment.line.cl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(for|while|if|else|elseif|return|def|function|type|new)\b</string>
			<key>name</key>
			<string>keyword.control.cl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(print|set)\b</string>
			<key>name</key>
			<string>support.function.cl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\$)([A-Za-z0-9_]+)</string>
			<key>name</key>
			<string>entity.name.function.cl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\@)([A-Za-z0-9_]+)</string>
			<key>name</key>
			<string>entity.name.function.cl</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.cl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.scope.cl</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\@[a-zA-Z_]+)\b:\b([a-zA-Z_\$\,\s]+)</string>
			<key>name</key>
			<string>meta.function.cl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;![^.]\.|:)\b(false|nil|true|math\.(pi|huge))\b|(?&lt;![.])\.{3}(?!\.)</string>
			<key>name</key>
			<string>constant.language.cl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;![^.]\.|:)\b(self)\b</string>
			<key>name</key>
			<string>variable.language.self.cl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\+|-|%|\*|\/|\^|==?|~=|&lt;=?|&gt;=?|&gt;|\:|(?&lt;!\.)\.{2}(?!\.)</string>
			<key>name</key>
			<string>keyword.operator.cl</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.cl</string>
	<key>uuid</key>
	<string>93E017CC-6F27-11D9-90EB-000D93589AF7</string>
</dict>
</plist>
